<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[1]=array(0,1,1,'6aaW6aG1');
$cfg_Cs[2]=array(0,1,1,'5YWz5LqO5oiR5Lus');
$cfg_Cs[3]=array(0,1,1,'5YWs5Y+45paw6Ze7');
$cfg_Cs[4]=array(0,1,1,'5Lqn5ZOB5Y+K5pyN5Yqh');
$cfg_Cs[5]=array(0,1,1,'6IGU57O75oiR5Lus');
$cfg_Cs[6]=array(0,1,1,'5Lq65omN5oub6IGY');
$cfg_Cs[7]=array(4,1,1,'6aOO6Zmp5o6n5Yi2566h55CG');
$cfg_Cs[8]=array(4,1,1,'5Zyo57q/5Lqn5ZOB');
$cfg_Cs[9]=array(4,1,1,'5pyN5Yqh5a6X5peo');
$cfg_Cs[12]=array(6,1,1,'56S+5Lya5bKX5L2N');
$cfg_Cs[13]=array(6,1,1,'5a6e5Lmg55Sf5bKX5L2N');
$cfg_Cs[10]=array(4,1,1,'566h55CG5pyN5Yqh');
$cfg_Cs[11]=array(2,1,1,'5b6Q57+g5p6X5b6X566A5LuL');
$cfg_Cs[15]=array(2,1,1,'6buE6LaF');
?>