<div class="product_ol product_item">
	<div class="content clearfix">
		<div class="pic">
			<img width="520" height="328" src="/uploads/150924/1-15092415210MR.jpg" style="width: 520px; height: 328px;" />
		</div>
		<div class="txt">
			<h2>[field:title/]</h2>
			<p>[field:description/]</p>
			<a href="[field:arcurl/]"><img alt="" src="/uploads/150617/1-15061G34531961.png" style="width: 124px; height: 32px;" /></a>
		</div>
	</div>
	</div>