<?php
$z[0]=Array("global","",52,79);
$z[0][4]['name']="cfg_indexurl";
$z[1]=Array("type","<li><a href=\"[field:typelink/]\">关于我们</a>",110,192);
$z[1][4]['typeid']="2";
$z[2]=Array("type","<li><a href=\"[field:typelink/]\">公司新闻</a></li>",453,540);
$z[2][4]['typeid']="3";
$z[3]=Array("type","<li><a href=\"[field:typelink/]\">产品及服务</a>",554,639);
$z[3][4]['typeid']="4";
$z[4]=Array("channel","\r\n                    <dd><a href=\"[field:typelink/]\">[field:typename/]</a></dd>\r\n                ",676,825);
$z[4][4]['type']="son";
$z[4][4]['typeid']="4";
$z[5]=Array("type","<li><a href=\"[field:typelink/]\">联系我们</a></li>",1323,1410);
$z[5][4]['typeid']="5";
$z[6]=Array("type","<li><a href=\"[field:typelink/]\">人才招聘</a></li>",1424,1511);
$z[6][4]['typeid']="6";

?>